# Generated by Django 5.1.5 on 2026-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menstrualcycle',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menstrualcycle',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menstrualcycle',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
